name: stopnow
description: "Aplicación para ayudar a las personas a dejar de fumar"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  supabase_flutter: ^2.8.4
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  path: ^1.8.3
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  connectivity_plus: ^6.1.4
  loading_animation_widget: ^1.3.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  vibration: ^3.1.3
  extended_text_field: ^16.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

# Configuración de splash screen
flutter_native_splash:
  color: "#ffffff" # Color de fondo
  image: assets/logo-fondo-azul.png # Imagen que quieres mostrar
  android_12:
    color: "#ffffff"
    image: assets/logo-fondo-azul.png
  web: false # No poner splash en Web

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo-fondo-azul.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # O puede ser una imagen
  adaptive_icon_foreground: "assets/logo-fondo-azul.png"
  remove_alpha_ios: true # Eliminar el fondo blanco de la imagen
  remove_alpha_android: true # Eliminar el fondo blanco de la imagen
