name: stopnow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  supabase_flutter: ^2.8.4
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# Configuración de splash screen
flutter_native_splash:
  color: "#ffffff" # Color de fondo
  image: assets/logo-fondo-azul.png # Imagen que quieres mostrar
  android_12:
    color: "#ffffff"
    image: assets/logo-fondo-azul.png
  web: false # No poner splash en Web

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo-fondo-azul.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # O puede ser una imagen
  adaptive_icon_foreground: "assets/logo-fondo-azul.png"
  remove_alpha_ios: true # Eliminar el fondo blanco de la imagen
  remove_alpha_android: true # Eliminar el fondo blanco de la imagen